version: "3.9"

services:
  backend:
    build:
      context: ./backend-tareas
    container_name: backend-tareas
    environment:
      PORT: ${PORT}
      MONGODB_URI: ${MONGODB_URI}
      JWT_SECRET: ${JWT_SECRET}
      CORS_ORIGIN: ${CORS_ORIGIN}
      NODE_ENV: production
    ports:
      - "${PORT}:${PORT}"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend-tareas
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL}
        VITE_SERVER_NAME: ${VITE_SERVER_NAME}
    container_name: frontend-tareas
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: unless-stopped

  mongo:
    image: mongo:7.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data:

# aaraya@gmail.com
# 12345
